In [2]:
import pandas as pd
import numpy as np

In [9]:
import os

In [10]:
os.listdir()

['.config', 'animal_data_dirty1[1].csv', 'sample_data']

In [15]:
df = pd.read_csv("animal_data_dirty1[1].csv",sep=";")

In [16]:
df.shape

(1011, 11)

In [17]:
df.head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony

In [18]:
df.columns

Index(['Animal type', 'Country', 'Weight kg', 'Body Length cm', 'Gender',
       'Animal code', 'Latitude', 'Longitude', 'Animal name',
       'Observation date', 'Data compiled by'],
      dtype='object')

In [19]:
df.dtypes

Animal type          object
Country              object
Weight kg           float64
Body Length cm      float64
Gender               object
Animal code         float64
Latitude            float64
Longitude           float64
Animal name          object
Observation date     object
Data compiled by     object
dtype: object

In [20]:
df.isnull().sum()

Animal type           20
Country               12
Weight kg             27
Body Length cm        27
Gender                19
Animal code         1011
Latitude              98
Longitude             98
Animal name          959
Observation date       0
Data compiled by       0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(167)

In [22]:
df['Animal type'].value_counts(dropna=False)

Animal type
red squirrel       543
hedgehog           274
lynx                61
European bison      49
red squirrell       22
NaN                 20
red squirel         14
lynx?               10
European bison™      6
European buster      4
European bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

In [23]:
df['Country'].value_counts(dropna=False)

Country
Poland            291
Germany           176
Slovakia          151
Hungary           146
Czech Republic    103
Austria            74
PL                 15
NaN                12
HU                 11
Hungry             10
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

In [24]:
df['Weight kg'].describe()

count     984.000000
mean       39.745503
std       156.290076
min        -0.252000
25%         0.293000
50%         0.331500
75%         0.800000
max      1100.000000
Name: Weight kg, dtype: float64

In [25]:
df['Body Length cm'].describe()

count    984.000000
mean      39.107724
std       58.628601
min      -19.000000
25%       19.000000
50%       21.000000
75%       23.000000
max      350.000000
Name: Body Length cm, dtype: float64

In [26]:
df['Observation date'].value_counts().head(20)

Observation date
01.03.2024    61
02.03.2024    47
06.04.2024    45
04.03.2024    43
02.04.2024    41
24.03.2024    28
21.03.2024    28
07.03.2024    25
11.03.2024    23
08.04.2024    20
05.04.2024    19
05.03.2024    19
11.04.2024    18
14.03.2024    17
22.03.2024    16
09.03.2024    16
19.03.2024    15
06.03.2024    14
15.04.2024    14
23.03.2024    14
Name: count, dtype: int64

In [27]:
df['Data compiled by'].value_counts(dropna=False)

Data compiled by
Anne Anthony     473
Bob Bobson       259
John Johnson     249
James Johnson     30
Name: count, dtype: int64

1. Diagnostico inicial
*problemas de calidad encontrados

1. * VALORES FALTANTES*; se encontraron valores ausentes en varia columnas del conjunto de datos. El caso mas significativo corresponde a la columna "animal name" con 959 valores faltantes.

2. * REGISTROS DUPLICADOS*; se identificaron 167 registros duplicados dentro del conjunto de datos.

3. * INCONSISTENCIAS EN LAS CATEGORIAS*; se encontraron diferentes formas de escribir algunos valores en las columnas "animal type" y "country". por ejemplo aparecen variantes como: "red squirrel" y "Red squirrel", asi como "poland y "pl".

4. * VALORES NUMERICOS INVALIDOS*; se encontraron valores negativos envariables que no deberian tener valores menores que cero, como el peso y la longitud corporal.

PUNTO 2-Limpieza de datos

In [42]:
df.isnull().sum()

Animal type           20
Country               12
Weight kg             27
Body Length cm        27
Gender                19
Animal code         1011
Latitude              98
Longitude             98
Animal name            0
Observation date       0
Data compiled by       0
dtype: int64

In [43]:
df['Animal name'] = df['Animal name'].fillna('Unknown')

In [44]:
df['Animal name'].isnull().sum()

np.int64(0)

In [45]:
df.columns

Index(['Animal type', 'Country', 'Weight kg', 'Body Length cm', 'Gender',
       'Animal code', 'Latitude', 'Longitude', 'Animal name',
       'Observation date', 'Data compiled by'],
      dtype='object')

In [46]:
df['Country'].isnull().sum()

np.int64(12)

In [47]:
df[df['Country'].isnull()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.02.2024,James Johnson
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.03.2024,James Johnson
563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.04.2024,James Johnson
833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.05.2024,James Johnson
934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.06.2024,James Johnson
956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.07.2024,James Johnson
963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.08.2024,James Johnson
968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.13.2024,James Johnson
969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.14.2024,James Johnson
970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.22.2024,James Johnson
971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,03.22.2024,James Johnson

In [48]:
list(df.columns)

['Animal type',
 'Country',
 'Weight kg',
 'Body Length cm',
 'Gender',
 'Animal code',
 'Latitude',
 'Longitude',
 'Animal name',
 'Observation date',
 'Data compiled by']

In [52]:
df['Country'] = df['Country'].fillna('Unknown')

In [54]:
df["Gender"].isnull().sum()

np.int64(19)

In [55]:
df["Gender"] = df["Gender"].fillna("Unknown")

In [56]:
df['Animal code'].isnull().sum()

np.int64(1011)

In [57]:
df["Animal code"] = df["Animal code"].fillna("Unknown")

In [58]:
df["Latitude"].isnull().sum()

np.int64(98)

In [59]:
df["Latitude"] = df["Latitude"].fillna(0)

In [60]:
df['Longitude'].isnull().sum()

np.int64(98)

In [61]:
df["Longitude"] = df["Longitude"].fillna(0)

In [62]:
df["Weight kg"].isnull().sum()

np.int64(27)

In [63]:
df['Weight kg'].median()

0.3315

In [64]:
df['Weight kg'] = df['Weight kg'].fillna(df['Weight kg'].median())

In [65]:
df['Body Length cm'].isnull().sum()

np.int64(27)

In [66]:
df['Body Length cm'].median()

21.0

In [67]:
df['Body Length cm'] = df['Body Length cm'].fillna(df['Body Length cm'].median())

In [68]:
df.duplicated().sum()

np.int64(167)

In [69]:
df = df.drop_duplicates()

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df['Animal type'].value_counts()

Animal type
red squirrel       387
hedgehog           274
lynx                61
European bison      49
red squirrell       16
red squirel         10
lynx?               10
European bison™      6
European buster      4
European bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

In [72]:
df['Animal type'].unique()

array([nan, 'European bison', 'European bison™', 'European bisson',
       'European buster', 'lynx', 'lynx?', 'red squirel', 'red squirrel',
       'red squirrell', 'hedgehog', 'wedgehod', 'ledgehod'], dtype=object)

In [73]:
df['Animal type'] = df['Animal type'].str.strip().str.lower()

/tmp/ipykernel_668/1678666720.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Animal type'] = df['Animal type'].str.strip().str.lower()

In [74]:
df['Animal type'].value_counts()

Animal type
red squirrel       387
hedgehog           274
lynx                61
european bison      49
red squirrell       16
red squirel         10
lynx?               10
european bison™      6
european buster      4
european bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

In [75]:
for animal in df['Animal type'].unique():
    print(repr(animal))

nan
'european bison'
'european bison™'
'european bisson'
'european buster'
'lynx'
'lynx?'
'red squirel'
'red squirrel'
'red squirrell'
'hedgehog'
'wedgehod'
'ledgehod'

In [76]:
df['Animal type'].value_counts(dropna=False)

Animal type
red squirrel       387
hedgehog           274
lynx                61
european bison      49
NaN                 19
red squirrell       16
red squirel         10
lynx?               10
european bison™      6
european buster      4
european bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

In [86]:
df = df.copy()

In [87]:
df['Animal type'].value_counts(dropna=False)

Animal type
red squirrel       403
hedgehog           274
lynx                61
european bison      59
NaN                 19
lynx?               10
red squirel         10
european buster      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

In [91]:
df.loc[:, "Animal type"] = df["Animal type"].replace({"lynx?": "lynx"})

In [97]:
df.loc[:, "Animal type"] = df["Animal type"].replace({"european booster": "european bison"})

In [98]:
df.loc[:, "Animal type"] = df["Animal type"].replace({"red squirrel": "squirrel"})

In [99]:
df.loc[:, "Animal type"] = df["Animal type"].replace({"wedgehod": "hedgehog"})

In [100]:
df.loc[:, "Animal type"] = df['Animal type'].replace({"european buster": "european bison"})

In [102]:
df.loc[:, "Animal type"] = df["Animal type"].replace({"ledgehod": "hedgehog"})

In [103]:
df['Animal type'].value_counts(dropna=False)

Animal type
squirrel          403
hedgehog          278
lynx               71
european bison     63
NaN                19
red squirel        10
Name: count, dtype: int64

In [104]:
df.loc[:, "Animal type"] = df["Animal type"].fillna("Unknown")

In [105]:
df['Animal type'].value_counts(dropna=False)

Animal type
squirrel          403
hedgehog          278
lynx               71
european bison     63
Unknown            19
red squirel        10
Name: count, dtype: int64

In [106]:
df['Country'].value_counts(dropna=False)

Country
Poland            182
Germany           173
Slovakia          151
Czech Republic    103
Hungary           103
Austria            74
Unknown            11
PL                 10
HU                  8
Hungry              7
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

In [129]:
df.loc[:, "Country"] = df["Country"].replace({"PL": "Poland"})

In [130]:
df.loc[:, "Country"] = df["Country"].replace({"HU": "Hungry"})

In [131]:
df.loc[:, "Country"] = df["Country"].replace({"CZ": "Czech Republic"})

In [132]:
df.loc[:, "Country"] = df["Country"].replace({"DE": "Germany"})

In [133]:
df.loc[:, "Country"] = df["Country"].replace({"Czech": "Czech Republic"})

In [135]:
df.loc[:, "Country"] = df["Country"].replace({"Hungry": "Hungary"})

In [143]:
df.loc[:, "Country"] = df["Country"].replace({"CC": "Czech Republic"})

In [123]:
for pais in df["Country"].unique():
    print(repr(pais))

'Unknown'
'Poland'
'Hungary'
'Germany'
'Slovakia'
'Czech Republic'
'Czech'
'Hungry'
'HU'
'Austria'
'Australia'
'CZ'
'DE'
'CC'

In [144]:
df['Country'].value_counts()

Country
Poland            192
Germany           178
Slovakia          151
Hungary           118
Czech Republic    116
Austria            74
Unknown            11
Australia           4
Name: count, dtype: int64

In [141]:
df.columns

Index(['Animal type', 'Country', 'Weight kg', 'Body Length cm', 'Gender',
       'Animal code', 'Latitude', 'Longitude', 'Animal name',
       'Observation date', 'Data compiled by'],
      dtype='object')

In [146]:
df.loc[df["Country"] == "CC"]

Empty DataFrame
Columns: [Animal type, Country, Weight kg, Body Length cm, Gender, Animal code, Latitude, Longitude, Animal name, Observation date, Data compiled by]
Index: []

In [147]:
df['Country'].value_counts(dropna=False)

Country
Poland            192
Germany           178
Slovakia          151
Hungary           118
Czech Republic    116
Austria            74
Unknown            11
Australia           4
Name: count, dtype: int64

In [149]:
df.loc[df["Country"] == "Australia"]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
295,hedgehog,Australia,0.800,24.0,not determined,Unknown,47.781689,14.386777,Unknown,14.03.2024,Bob Bobson
370,hedgehog,Australia,0.600,14.0,female,Unknown,47.781248,14.382649,Unknown,21.03.2024,Bob Bobson
583,squirrel,Australia,0.266,20.0,female,Unknown,47.781632,14.382365,Unknown,05.04.2024,Bob Bobson
688,squirrel,Australia,0.310,23.0,male,Unknown,47.856092,15.083547,Unknown,11.04.2024,Bob Bobson

In [150]:
df.loc[df["Country"] == "Australia"].T

                             295         370         583         688
Animal type             hedgehog    hedgehog    squirrel    squirrel
Country                Australia   Australia   Australia   Australia
Weight kg                    0.8         0.6       0.266        0.31
Body Length cm              24.0        14.0        20.0        23.0
Gender            not determined      female      female        male
Animal code              Unknown     Unknown     Unknown     Unknown
Latitude               47.781689   47.781248   47.781632   47.856092
Longitude              14.386777   14.382649   14.382365   15.083547
Animal name              Unknown     Unknown     Unknown     Unknown
Observation date      14.03.2024  21.03.2024  05.04.2024  11.04.2024
Data compiled by      Bob Bobson  Bob Bobson  Bob Bobson  Bob Bobson

In [151]:
df['Gender'].value_counts(dropna=False)

Gender
male              423
female            401
Unknown            15
not determined      5
Name: count, dtype: int64

In [153]:
df["Animal code"].value_counts(dropna=False)

Animal code
Unknown    844
Name: count, dtype: int64

In [154]:
df[["Latitude"]].isna().sum()

Latitude    0
dtype: int64

In [155]:
df[["Longitude"]].isna().sum()

Longitude    0
dtype: int64

In [157]:
df.loc[df["Weight kg"] < 0, ["Weight kg"]]

Empty DataFrame
Columns: [Weight kg]
Index: []

In [159]:
df.loc[df["Weight kg"] < 0, ["Weight kg"]] = np.nan

In [160]:
df["Weight kg"] = df["Weight kg"].fillna(df["Weight kg"].median())

In [161]:
df["Weight kg"].min()

0.0

In [162]:
df.loc[df['Body Length cm'] < 0, ["Body Length cm"]]

     Body Length cm
47            -16.0
124           -19.0
162           -19.0
225           -19.0

In [163]:
df.loc[df['Body Length cm'] < 0, ["Body Length cm"]] = np.nan

In [164]:
df['Body Length cm'] = df['Body Length cm'].fillna(df['Body Length cm'].median())

In [167]:
df['Body Length cm'].min()

11.0

In [168]:
df.isna().sum()

Animal type         0
Country             0
Weight kg           0
Body Length cm      0
Gender              0
Animal code         0
Latitude            0
Longitude           0
Animal name         0
Observation date    0
Data compiled by    0
dtype: int64

In [169]:
df.duplicated().sum()

np.int64(0)

In [170]:
df['Animal type'].value_counts(dropna=False)

Animal type
squirrel          403
hedgehog          278
lynx               71
european bison     63
Unknown            19
red squirel        10
Name: count, dtype: int64

In [171]:
df['Country'].value_counts(dropna=False)

Country
Poland            192
Germany           178
Slovakia          151
Hungary           118
Czech Republic    116
Austria            74
Unknown            11
Australia           4
Name: count, dtype: int64

In [172]:
df["weight category"] = np.where(df['Weight kg'] >= 1,"1 kg or more","less than 1 kg")

In [173]:
np.median(df['Weight kg'])

np.float64(0.344)

* MEDIDA ESTADISTICA CON NUMPY
La mediana del peso de los animales es de 0.344 kg. Este valor representa el punto central de las observaciones de peso despues de realizar la limpieza de los datos.

In [174]:
df.groupby("Animal type").size()

Animal type
Unknown            19
european bison     63
hedgehog          278
lynx               71
red squirel        10
squirrel          403
dtype: int64

In [175]:
df.groupby("Animal type")["Weight kg"].mean()

Animal type
Unknown             0.312868
european bison    588.396825
hedgehog            0.792426
lynx               23.267606
red squirel         0.302700
squirrel            0.295730
Name: Weight kg, dtype: float64

In [176]:
df.groupby("Animal type")["Weight kg"].mean().round(2)

Animal type
Unknown             0.31
european bison    588.40
hedgehog            0.79
lynx               23.27
red squirel         0.30
squirrel            0.30
Name: Weight kg, dtype: float64

In [177]:
df.groupby("Country")["Weight kg"].mean().round(2)

Country
Australia           0.49
Austria             1.94
Czech Republic     74.50
Germany             0.46
Hungary             2.87
Poland            130.00
Slovakia           32.45
Unknown             0.33
Name: Weight kg, dtype: float64

In [178]:
df.groupby("Animal type")["Body Length cm"].mean().round(2)

Animal type
Unknown            20.74
european bison    244.24
hedgehog           20.24
lynx               82.90
red squirel        20.00
squirrel           20.55
Name: Body Length cm, dtype: float64

*INTERPRETACION DE RESULTADOS
Squirrel es el tipo de animal con mayor numero de observaciones, con 403 registros,seguido de Hedgehog con 278. Esto indica que esta dos categorias concentran la mayor parte de las obcervaciones de el conjunto de datos.

2-European bison precenta el mayor peso promedio, con 588.40 kg muy por encima de lynx, cuyo promedio es de 23.27 kg. Esto muestra una diferencia considerable de tamaño y peso entre los tipos de animales analizados.

3-Poland representa el mayor peso promedio del pais, con 130.00 kg seguido de czech republic con74.50 kg y slovakia con 32.45 kg. eso indica que las observaciones registradas en estos paises incluyen, enpromedio, animales de mayor peso.

4-European Bison tambien presenta la mayor longitud corporal promedio, con 244.24 cm, mientras que lynx alcanza 82.90 cm. Esto es consistente con el mayor peso promedio del Europan bison y evidencia una diferencia marcada entre tamaño entre las especies.

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 844 entries, 0 to 1010
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       844 non-null    object
 1   Country           844 non-null    object
 2   Weight kg         844 non-null    float64
 3   Body Length cm    844 non-null    float64
 4   Gender            844 non-null    object
 5   Animal code       844 non-null    object
 6   Latitude          844 non-null    float64
 7   Longitude         844 non-null    float64
 8   Animal name       844 non-null    object
 9   Observation date  844 non-null    object
 10  Data compiled by  844 non-null    object
 11  weight category   844 non-null    object
dtypes: float64(4), object(8)
memory usage: 85.7+ KB

In [187]:
df.shape

(844, 12)

In [199]:
print("valores negativos en peso:", (df["Weight kg"] < 0).sum())
print("valores negativos en longitud:", (df["Body Length cm"] <0).sum())

valores negativos en peso: 0
valores negativos en longitud: 0

In [200]:
df.duplicated().sum()

np.int64(0)

Verificación de la limpieza

Después de realizar el proceso de limpieza se verificó que:

- No quedan valores faltantes en las columnas del DataFrame.
- No quedan registros duplicados.
- No existen valores negativos en "Weight, kg".
- No existen valores negativos en "Body length, cm".
- Las categorías de "animal type" y "Country" fueron estandarizadas en los casos identificados.
- El DataFrame final contiene 844 registros y 12 columnas.

In [202]:
df.to_csv("animal_data_cleaned.csv",index=False)

In [204]:
import os
os.path.exists("animal_data_cleaned.csv")

True

In [205]:
from google.colab import files
files.download("animal_data_cleaned.csv")